-- metadata (version & date)
INSERT INTO metadata (version, date) 
VALUES ("0.5", "2018-09-09 17:17:17");

-- glossaire
INSERT OR REPLACE INTO glossaire (abreviation, description)
VALUES 
   ('G','contient du gluten'),
   ('L','contient des produits laitiers')
   ('V','convient aux végétariens'),
   ('C','contient des crustacés')
   ('A','contient des arachides'),
   ('S','contient du soja')
   ('F','contient des fruits à coques'),
   ('M','contient de la moutarde'),
   ('O',"contient de l'oeuf"),
   ('J','contient du sésame'),
   ('P','contient du poisson'),
   ('Alcool','Alcools -- ex. vin, etc.'),
   ('Boisson','Boissons -- ex. eau'),
   ('Cereale','Cereales -- ex. riz, pâtes, blé'),
   ('Feculent','Feculents -- ex. patate douce, patate'),
   ('Fruit de mer','Fruits de mer -- ex. crevettes, crabe, langouste'),
   ('Fruit et Fruit sec','Fruits et fruits secs -- ex: noisette, raisin sec, airelles'),
   ('Legume','Legumes -- ex: navet, carotte, laitue'),
   ('Matiere Grasse','Matieres grasses -- ex. huile d\'olive, pas beurre'),
   ('Oeuf','Oeuf -- ex. oeuf, jaune d\'oeuf'),
   ('PB','Poisson Blanc -- ex. Merlan, Loup'),
   ('PG','Poisson Gras -- ex. Saumon, Truite'),
   ('Produit Laitier','Produits laitiers -- ex. lait, fromage, yaourts'),
   ('Sauce et condiment','Sauces et condiments -- ex. Vinaigre, bouillon ... epices, arômates, herbes, moutarde'),
   ('Sucre','Sucres -- ex. Miel'),
   ('VB','Viande Blanche -- ex. Poulet, veau, lapin'),
   ('VR','Viande Rouge -- ex. Boeuf, agneau');

-- ingredients
INSERT OR REPLACE INTO ingredient (nomIngr, groupe, kcal)
VALUES 
   ('aubergine','Legume',NULL),
   ('avocat','Legume',NULL),
   ('basilic','Sauce et condiment',NULL),
   ('blette','Legume',NULL),
   ('betterave cuite','Legume',NULL),
   ('beurre','Matiere Grasse',NULL),
   ('blanc de poulet','VB',NULL),
   ('blette','Legume',NULL),
   ('boeuf','VR',NULL),
   ('bouillon de boeuf','VR,Sauce et condiment',NULL),
   ('bouillon de veau','VB,Sauce et condiment',NULL),
   ('bouillon de volaille','VB,Sauce et condiment',NULL),
   ('brocoli','Legume',NULL),
   ('brocoli chinois','Legume',NULL),
   ('capres','Sauce et condiment',NULL),
   ('carotte','Legume',NULL),
   ('chair a saucisse','VB',NULL),
   ('champignon','Legume',NULL),
   ('champignon de Paris','Legume',NULL),
   ('fromage de chevre frais','Produit Laitier',NULL),
   ('choucroute cuite','Legume',NULL),
   ('citron','Legume',NULL),
   ('citron confit','Legume',NULL),
   ('citron jaune','Legume',NULL),
   ('citron vert','Legume',NULL),
   ('collier d\'agneau','VR',NULL),
   ('concentre de tomates','Legume',NULL),
   ('confit de canard','VB',NULL),
   ('coriandre','Sauce et condiment',NULL),
   ('cote de boeuf','VR',NULL),
   ('cote de veau','VB',NULL),
   ('coulis de tomates','Legume',NULL),
   ('courgette','Legume',NULL),
   ('creme','Produit Laitier',NULL),
   ('creme fraiche','Produit Laitier',NULL),
   ('creme liquide','Produit Laitier',NULL),
   ('creme semi epaisse','Produit Laitier',NULL),
   ('crevette decortiquee','Fruit de mer',NULL),
   ('cuisse de poulet','VB',NULL),
   ('cumin','Sauce et condiment',NULL),
   ('curcuma','Sauce et condiment',NULL),
   ('curry','Sauce et condiment',NULL),
   ('eau','Boisson',NULL),
   ('echalote','Sauce et condiment',NULL),
   ('emmental','Produit Laitier',NULL),
   ('emmental rape','Produit Laitier',NULL),
   ('endive','Legume',NULL),
   ('epices a couscous','Sauce et condiment',NULL),
   ('epices a colombo','Sauce et condiment',NULL),
   ('epinard','Legume',NULL),
   ('escalope de poulet','VB',NULL),
   ('farine','Cereale',NULL),
   ('fenouil','Legume',NULL),
   ('feta','Produit Laitier',NULL),
   ('feuille de lasagne','Cereale',NULL),
   ('filet de poulet','VB',NULL),
   ('fleur de sel','Sauce et condiment',NULL),
   ('fromage aux fines herbes','Produit Laitier',NULL),
   ('fromage de chevre','Produit Laitier',NULL),
   ('fromage rape','Produit Laitier',NULL),
   ('gambas','Fruit de mer',NULL),
   ('gingembre','Sauce et condiment',NULL),
   ('gousse d\'ail','Sauce et condiment',NULL),
   ('grana padano','Produit Laitier',NULL),
   ('fenouil','Legume',NULL),
   ('gruyere rape','Produit Laitier',NULL),
   ('harissa','Sauce et condiment',NULL),
   ('huile d\'arachide','Matiere grasse',NULL),
   ('huile d\'olive','Matiere grasse',NULL),
   ('huile de noix','Matiere grasse',NULL),
   ('jambon','VB',NULL),
   ('jaune d\'oeuf',NULL,'Oeuf',NULL),
   ('joue de boeuf','VR',NULL),
   ('lait','Produit Laitier',NULL),
   ('lait de coco','Produit Laitier',NULL),
   ('lait ecreme','Produit Laitier',NULL),
   ('lard','VB',NULL),
   ('lardons','VB',NULL),
   ('laurier','Sauce et condiment',NULL),
   ('loup frais','PB',NULL),
   ('merguez','VR',NULL),
   ('miel','Sucre',NULL),
   ('moutarde','Sauce et condiment',NULL),
   ('mozzarella','Produit Laitier',NULL),
   ('muscade','Sauce et condiment',NULL),
   ('navet','Legume',NULL),
   ('noisette','Fruit et Fruit sec',NULL),
   ('oeuf','Oeuf',NULL),
   ('oignon rouge','Legume',NULL),
   ('oignon','Legume',NULL),
   ('oignon nouveau','VB',NULL),
   ('oignon rouge','Legume',NULL),
   ('olive','Fruit et fruit sec',NULL),
   ('olive noire','Fruit et fruit sec',NULL),
   ('pain','Cereale',NULL),
   ('paleron de boeuf','VR',NULL),
   ('parmesan','Produit Laitier',NULL),
   ('parmesan rape','Produit Laitier',NULL),
   ('patate douce','Feculent',NULL),
   ('pate feuilletee','Cereale',NULL),
   ('pates','Cereale',NULL),
   ('pate feuilletee','Cereale',NULL),
   ('pates fusilli','Cereale',NULL),
   ('cabillaud','PB',NULL),
   ('penne rigate','Cereale',NULL),
   ('persil','Sauce et condiment',NULL),
   ('pesto','Sauce et condiment',NULL),
   ('pilon de poulet','VB',NULL),
   ('piment de cayenne','Sauce et condiment',NULL),
   ('piment doux','Sauce et condiment',NULL),
   ('poireau','Legume',NULL),
   ('pois chiches','Feculent',NULL),
   ('pois gourmands','Legume',NULL),
   ('poivron jaune','Legume',NULL),
   ('poivron rouge','Legume',NULL),
   ('poivron','Legume',NULL),
   ('pomme de terre','Feculent',NULL),
   ('porc','VB',NULL),
   ('potimarron','Legume',NULL),
   ('ricotta','Produit Laitier',NULL),
   ('riz a risotto','Cereale',NULL),
   ('riz long','Cereale',NULL),
   ('safran','Sauce et condiment',NULL),
   ('salicorne','Legume',NULL),
   ('sauce soja','Sauce et condiment',NULL),
   ('sauce teriyaki','Sauce et condiment',NULL),
   ('saumon fume','PG',NULL),
   ('spaghetti','Cereale',NULL),
   ('tagliatelles','Cereale',NULL),
   ('thon','PG',NULL),
   ('thym','Sauce et condiment',NULL),
   ('tomate','Legume',NULL),
   ('tomate cerise','Legume',NULL),
   ('tomate confite','Legume',NULL),
   ('tomate pelee','Legume',NULL),
   ('truite fumee','PG',NULL),
   ('veau','VB',NULL),
   ('vin','Alcool',NULL),
   ('vin rouge','Alcool',NULL),
   ('vinaigre','Sauce et condiment',NULL),
   ('vinaigre de cidre','Sauce et condiment',NULL),
   ('vinaigrette','Sauce et condiment',NULL),
   ('Worcestershire sauce','Sauce et condiment',NULL);

-- designation (ex-NomDePlat)
INSERT OR REPLACE INTO designation (nomPlat, regime)
VALUES 
   ('agneau a l\'anglaise','G,S,J,P'),
   ('aiguillettes de poulet aux legumes','O,L'),
   ('aubergines farcies aux legumes','L'),
   ('baked potatoes au four','L,V'),
   ('boeuf bourgignon',NULL),
   ('boeuf braise aux carottes',NULL),
   ('boeuf carottes',NULL),
   ('canelloni au fenouil','L,G'),
   ('carottes au curry et aux petites lardons','L'),
   ('clafouti brocoli et tomates cerises','L,O'),
   ('colombo de poulet',NULL),
   ('cotes de boeuf et aubergines grillees',NULL),
   ('cotes de veau au riz et aux aubergines','G'),
   ('courgettes farcies','L'),
   ('couscous poulet merguez',NULL),
   ('crottins chauds','G,L'),
   ('crumble aux courgettes','L,G'),
   ('Endives au jambon','L,G'),
   ('gratin de blettes a la provencale','L,G,V'),
   ('gratin de potimarron','L,O'),
   ('loup au fenouil','P'),
   ('omelette a la salicorne','O,L'),
   ('papillotte de poisson a l\'avocat','P'),
   ('parmentier de canard a la puree de carottes',NULL),
   ('parmentier de patate douce au poisson','L,P'),
   ('penne rigate au saumon','L,G,P'),
   ('quiche aux epinards chevre et saumon','G,L,P'),
   ('quiche lorraine','G,L,O'),
   ('quiche truite fumee aux courgettes et mozarella','G,L,O,P'),
   ('ragout boeuf carottes','G'),
   ('risotto aux legume et jambon','S,G'),
   ('salade de betteraves','V'),
   ('salade de brocolis aux tomates cerises','V,F'),
   ('salade de fusili crevette et avocat','G,M'),
   ('salade de pates tomates et mozzarella','V,G,L'),
   ('salade tomate thon basilique','O,P'),
   ('salade tomates feta poivrons','L'),
   ('spaghetti au chevre','G,L,V'),
   ('spaghetti aux blettes','G,L'),
   ('spaghetti carbonara','L,G,O'),
   ('spaghettis aux gambas','C,G,L'),
   ('tagine de veau a la patate douce',NULL),
   ('tagliatelles au poulet','G,A,S'),
   ('tajine de veau aux carottes',NULL),
   ('tarte au poulet fenouil et poireau','G,O,L'),
   ('thon au fenouil et aux tomates','P'),
   ('tian aux legumes','V,L'),
   ('tourte a la choucroute','L,G'),
   ('patates garnies au thon au four',NULL);

